### ISSUE TITLE
dwarffortress executable won't start, saying "undefined symbol" (running on archlinux)

### ISSUE THREAD

**Issue by kindaro** [svenstaro/dwarf_fortress_unfuck#17]
Hi.

I just built it on my Archlinux laptop and it says:
```
Loading bindings from data/init/interface.txt
Unknown binding: STRING_A127
./libs/Dwarf_Fortress: symbol lookup error: ./libs/Dwarf_Fortress: undefined symbol: _Z25get_slot_and_addbit_ucharRhRlll
```

Can it be fixed?

**Comment by svenstaro** [comment]
No idea what is happening there. Other people don't seem to have that problem. You seem to be using different dynamic libraries here. Make sure your system is clean.

**Comment by svenstaro** [comment]
Going to close this. I assume it's fixed with the new release.

**Comment by Nyefan** [comment]
I am getting this error as well:

[username@computername ~]$ dwarffortress 
Loading bindings from data/init/interface.txt
Unknown binding: HOTKEY_GLASS_INSTRUMENT
Unknown binding: HOTKEY_CRAFTS_MAT_INSTRUMENT
Unknown binding: UNITJOB_VIEW
Unknown binding: STRING_A127
./libs/Dwarf_Fortress: symbol lookup error: ./libs/Dwarf_Fortress: undefined symbol: _Z25get_slot_and_addbit_ucharRhRlll

By commenting out those binds in ./data/init/interface.txt, I can suppress the unknown binding errors, but I haven't figured out how to get past the symbol lookup error yet.

**Comment by svenstaro** [comment]
Does it work if you move the .dwarffortress dir in $HOME?

**Comment by Nyefan** [comment]
I don't have a .dwarffortress dir there.  That would only be created if the executable successfully launched, yes?
