### ISSUE TITLE
are you aware of

### ISSUE THREAD

**Issue by rofl0r** [svenstaro/dwarf_fortress_unfuck#20]
https://github.com/rofl0r/df-libgraphics

basically doing the same since 1974. however with
- support for musl libc
- support for netbsd curses
- support for compile without openGL
- support for compile without GTK

**Comment by rofl0r** [comment]
(hint: there's one branch per major DF release)

**Comment by svenstaro** [comment]
I wasn't aware of that. I'm going to check it out. Thanks!

**Comment by lethosor** [comment]
Looks neat. One note on the readme - Toady actually used GCC 4.5 until 0.43.05, when he switched to 4.8 on Linux (and kept 4.5 on OS X).

**Comment by rofl0r** [comment]
interesting. i seem to recall that running objdump or strings on 0.43.05 binary (comment section) said it was 4.6 but i may be wrong. what i know definitely is that 4.7 is compatible (since 4.7 is the standard compiler of sabotage linux, my distro).

**Comment by lethosor** [comment]
Running `strings` on libs/Dwarf_Fortress gives a bunch of occurrences of `GCC: (GNU) 4.5.1`. You should be able to use a libgraphics built with any newer version of GCC, though, as long as you're also using a newer libstdc++ (and for GCC 5+, you'll need [this flag](https://github.com/svenstaro/dwarf_fortress_unfuck/commit/a89840de15d9d2090c49159e5bfc84f7520814ad)). For all I know, 4.5 and 4.6 could be interchangeable - I know 4.5 and 4.8 aren't, but I haven't worked with 4.6 much.

**Comment by rofl0r** [comment]
> You should be able to use a libgraphics built with any newer version of GCC, though, as long as you're also using a newer libstdc++

maybe that depends on how libstdc++ was built; probably there is some way to build it with versioned symbols for older C++ ABI and then it will work, and big distros might default to doing it that way.
