### ISSUE TITLE
Release build change breaks dfhack

### ISSUE THREAD

**Issue by numinit** [svenstaro/dwarf_fortress_unfuck#22]
Hey there,

I get the following when running the latest dfhack:

```
/[...]/libs/Dwarf_Fortress: symbol lookup error: /[...]/hack/libdfhack.so: undefined symbol: _ZN8rendererD1Ev
```

I ran `nm -D` on the built libgraphics.so and don't see `renderer::~renderer()` anywhere.

**Comment by numinit** [comment]
I've tried a couple things (including passing -fno-inline and -fkeep-inlined-functions in CXXFLAGS), and it seems to still get removed :-(

**Comment by svenstaro** [comment]
Should be fixed, can you check?

**Comment by rofl0r** [comment]
> Should be fixed

please provide commit hash

**Comment by lethosor** [comment]
From https://github.com/svenstaro/dwarf_fortress_unfuck/commits/master, literally the only commit after the change from debug to release is https://github.com/svenstaro/dwarf_fortress_unfuck/commit/b16cd090c2eb9e0dfe3c1f1d493b58b9a95ab1be

**Comment by svenstaro** [comment]
I got confirmation that this works from the related Arch bug. Closing.
