### ISSUE TITLE
Final 0.47 tag

### ISSUE THREAD

**Issue by numinit** [svenstaro/dwarf_fortress_unfuck#29]
Hi there,

I maintain this for nixpkgs and it would be good if we could get a "0.47.05-final" tag or similar on master. We maintain builds for older DF versions and it would be good to have a final tag we could refer to.

Thanks!

**Comment by svenstaro** [comment]
Alright, here you go.

> This is a pull request. All craftsdwarfship is of the highest quality. It menaces with spikes of Nix and bash. On the pull request are several derivations.

Hah!

**Comment by numinit** [comment]
Thanks!
